using System.CodeDom.Compiler;
using zms9110750.StaticMethodAsExtensionGenerator.Builder.Helper;

namespace zms9110750.StaticMethodAsExtensionGenerator.Builder;

class StaticNamespaceBuilder(IndentedTextWriter writer)
{
    public IndentedTextWriter Writer { get; } = writer ?? throw new ArgumentNullException(nameof(writer));

    private static readonly SymbolDisplayFormat QualifiedFormat = SymbolDisplayFormat.FullyQualifiedFormat;

    public void GenerateAll(string nsName, List<TypeExtensionInfo> types)
    {
        using DeferredActionScope deferredActionScope = new();

        Writer.WriteLine("// <auto-generated />");
        Writer.WriteLine();

        var genNs = nsName.Length > 0
            ? $"zms9110750.Extensions.Generator.{nsName}"
            : "zms9110750.Extensions.Generator";
        Writer.WriteLine($"namespace {genNs}");
        Writer.AppendOpenBracket(deferredActionScope);

        foreach (var info in types)
        {
            using DeferredActionScope classScope = new();
            Writer.WriteLine($"internal static class {info.Type.Name}Extensions");
            Writer.AppendOpenBracket(classScope);

            foreach (var method in info.Methods)
            {
                GenerateMethod(method, info.Type);
            }
        }
    }

    private void GenerateMethod(IMethodSymbol method, INamedTypeSymbol owner)
    {
        var parameters = method.Parameters;
        var cref = $"{FullyQualifiedName(owner)}.{method.Name}({string.Join(", ", parameters.Select(p => FullyQualifiedName(p.Type)))})";

        Writer.WriteLine($"/// <inheritdoc cref=\"{cref}\" />");

        Writer.Write($"internal static {FullyQualifiedName(method.ReturnType)} {method.Name}(this {FullyQualifiedName(parameters[0].Type)} {EscapeKeywordIfNeeded(parameters[0].Name)}");
        for (int i = 1; i < parameters.Length; i++)
        {
            Writer.Write(", ");
            if (parameters[i].IsParams)
            {
                Writer.Write("params ");
            }
            Writer.Write($"{FullyQualifiedName(parameters[i].Type)} {EscapeKeywordIfNeeded(parameters[i].Name)}");
        }
        Writer.WriteLine(")");

        using DeferredActionScope deferredActionScope = new();
        Writer.AppendOpenBracket(deferredActionScope);
        {
            Writer.Write($"{(method.ReturnsVoid ? "" : "return ")}{FullyQualifiedName(owner)}.{method.Name}(");
            for (int i = 0; i < parameters.Length; i++)
            {
                if (i > 0)
                {
                    Writer.Write(", ");
                }
                Writer.Write(EscapeKeywordIfNeeded(parameters[i].Name));
            }
            Writer.WriteLine(");");
        }
        Writer.WriteLine();
    }

    private static string FullyQualifiedName(ITypeSymbol type)
    {
        return type.ToDisplayString(QualifiedFormat);
    }

    private static string EscapeKeywordIfNeeded(string name)
    {
        return SyntaxFacts.IsKeywordKind(SyntaxFacts.GetKeywordKind(name)) ? "@" + name : name;
    }
}
