using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Security.Cryptography;
using System.Text;
using zms9110750.InterfaceImplAsExtensionGenerator.Builder.Helper;
using zms9110750.InterfaceImplAsExtensionGenerator.Builder.Member;

namespace zms9110750.InterfaceImplAsExtensionGenerator.Builder;

internal class InterfaceBuilder(ExtensionConfig config, IndentedTextWriter writer, Action<Diagnostic> reportDiagnostic, LanguageVersion languageVersion = default)
{
    public InterfaceBuilder(INamedTypeSymbol interfaceSymbol, IndentedTextWriter writer, Action<Diagnostic> reportDiagnostic, LanguageVersion languageVersion = default)
        : this(new ExtensionConfig(interfaceSymbol), writer, reportDiagnostic, languageVersion)
    {
    }
    public InterfaceBuilder(INamedTypeSymbol typeClass, ExtensionForAttribute attribute, IndentedTextWriter writer, Action<Diagnostic> reportDiagnostic, LanguageVersion languageVersion = default)
      : this(new ExtensionConfig(typeClass, attribute), writer, reportDiagnostic, languageVersion)
    {
    }

    public IndentedTextWriter Writer { get; } = writer ?? throw new ArgumentNullException(nameof(writer));
    public Action<Diagnostic> ReportDiagnostic { get; } = reportDiagnostic ?? throw new ArgumentNullException(nameof(reportDiagnostic));
    public ExtensionConfig Config { get; } = config ?? throw new ArgumentNullException(nameof(config));
    public TypeParameterBuild TypeBuild { get; } = new TypeParameterBuild(config.TypeSymbol);

    public void GenerateSource()
    {
        using DeferredActionScope deferredActionScope = new DeferredActionScope();
        Writer.WriteLine("// <auto-generated />");
        Writer.WriteLine("// Language Version: " + languageVersion);
        if (Config.NamespaceName != "")
        {
            Writer.WriteLine($"namespace {Config.NamespaceName}");
            Writer.AppendOpenBracket(deferredActionScope);
        }
        if (Config.UsePublic)
        {
            Writer.Write("public ");
        }
        Writer.WriteLine($"static partial class {Config.ClassName.EscapeKeywords()}");
        Writer.AppendOpenBracket(deferredActionScope);
        switch (Config.UseSyntax)
        {
            case ExtensionSyntaxVersion.Auto when languageVersion >= LanguageVersion.CSharp14:
            case ExtensionSyntaxVersion.ExtensionBlock:
                GenerateBlock();
                break;
            case ExtensionSyntaxVersion.Auto:
            case ExtensionSyntaxVersion.ExtensionMethod:
                GenerateMethod();
                break;
            case ExtensionSyntaxVersion.Both:
                Writer.WriteLineNoTabs("#if NET10_0_OR_GREATER");
                GenerateBlock();
                Writer.WriteLineNoTabs("#else");
                GenerateMethod();
                Writer.WriteLineNoTabs("#endif");
                break;
            default:
                throw new InvalidOperationException($"Unsupported ExtensionSyntaxVersion: {Config.UseSyntax}");
        }
    }

    void GenerateBlock()
    {
        Writer.Write("extension");
        if (TypeBuild.GetTypeParametersNameClassOnly().Any())
        {
            Writer.Write("<");
            Writer.Write(string.Join(", ", TypeBuild.GetTypeParametersNameClassOnly()));
            Writer.Write(">");
        }
        Writer.WriteLine($"({TypeBuild.FullyQualifiedFormat()} {Config.InstanceName})");
        Writer.Indent++;
        Writer.WriteSources(TypeBuild.AppendConstraintClausesClassOnly().ToString());
        Writer.Indent--;

        using DeferredActionScope deferredActionScope = new DeferredActionScope();
        Writer.AppendOpenBracket(deferredActionScope);

        foreach (var item in config.TypeSymbol.GetMembers())
        {
            var memberBuilder = MemberBuilder.Creat(this, item);
            if (memberBuilder.IsValid)
            {
                memberBuilder.GenerateMemberExtensionBlock();
            }
        }
    }
    void GenerateMethod()
    {
        foreach (var item in config.TypeSymbol.GetMembers())
        {
            var memberBuilder = MemberBuilder.Creat(this, item);
            if (memberBuilder.IsValid)
            {
                memberBuilder.GenerateMemberExtensionMethod();
            }
        }
    }
}

